# Pre-commit hooks для NixOS конфигурации (2025 best practices)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict

  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt
        
  - repo: https://github.com/kamadorueda/alejandra
    rev: 4.0.0
    hooks:
      - id: alejandra-check
      
  - repo: https://github.com/nix-community/statix
    rev: v0.5.8
    hooks:
      - id: statix-check

  - repo: local
    hooks:
      - id: nix-flake-check
        name: nix flake check
        entry: nix flake check
        language: system
        files: \.(nix|lock)$
        pass_filenames: false