{
  imports = [
    ./brave
    ./code-cursor
    ./exodus
    ./fastfetch
    ./homevpnctl
    ./keepassxcctl
    ./s3fsctl
    ./xrayctl
    ./bottom.nix
    ./btop.nix
    ./fish.nix
    ./git-sync-obsidian.nix
    ./git-sync-wallpapers.nix
    ./git.nix
    ./htop.nix
    ./kitty.nix
    ./ssh.nix
    ./yazi.nix
  ];
}
